///|
pub extend LoadRequest with ToJson::{to_json}

///|
pub extend LoadRequest with @json.FromJson::{from_json}

///|
pub extend ConnectionReply with ToJson::{to_json}

///|
pub extend ConnectionReply with @json.FromJson::{from_json}

///|
pub extend ExecuteRequest with ToJson::{to_json}

///|
pub extend ExecuteRequest with @json.FromJson::{from_json}

///|
pub extend ExecuteReply with ToJson::{to_json}

///|
pub extend ExecuteReply with @json.FromJson::{from_json}

///|
pub extend SelectReply with ToJson::{to_json}

///|
pub extend SelectReply with @json.FromJson::{from_json}
