///|
pub extend FsPathRequest with ToJson::{to_json}

///|
pub extend FsPathRequest with @json.FromJson::{from_json}

///|
pub extend FsWriteRequest with ToJson::{to_json}

///|
pub extend FsWriteRequest with @json.FromJson::{from_json}

///|
pub extend FsMkdirRequest with ToJson::{to_json}

///|
pub extend FsMkdirRequest with @json.FromJson::{from_json}

///|
pub extend FsRemoveRequest with ToJson::{to_json}

///|
pub extend FsRemoveRequest with @json.FromJson::{from_json}

///|
pub extend FsReaddirRequest with ToJson::{to_json}

///|
pub extend FsReaddirRequest with @json.FromJson::{from_json}

///|
pub extend FsTmpdirRequest with ToJson::{to_json}

///|
pub extend FsTmpdirRequest with @json.FromJson::{from_json}

///|
pub extend FsBoolReply with ToJson::{to_json}

///|
pub extend FsBoolReply with @json.FromJson::{from_json}

///|
pub extend FsStringReply with ToJson::{to_json}

///|
pub extend FsStringReply with @json.FromJson::{from_json}

///|
pub extend FsReadReply with ToJson::{to_json}

///|
pub extend FsReadReply with @json.FromJson::{from_json}

///|
pub extend FsListReply with ToJson::{to_json}

///|
pub extend FsListReply with @json.FromJson::{from_json}

///|
pub extend FsReply with ToJson::{to_json}

///|
pub extend FsReply with @json.FromJson::{from_json}

///|
pub extend FsStatReply with ToJson::{to_json}

///|
pub extend FsStatReply with @json.FromJson::{from_json}
